"""New migration

Revision ID: 7676c156fbfd
Revises: 88e0a0f7eed8
Create Date: 2022-08-26 07:19:36.114962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7676c156fbfd'
down_revision = '88e0a0f7eed8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
